### PR TITLE
Added some of the test cases and modified the existing test cases by AT2...

### PR DESCRIPTION
**Pull request by savann2022**
Hi AL,

I have committed some of the new test cases and some modifications in existing test cases to BranchY. Please review and approve.

Regards,
AT2

### CODE REVIEW

**Comment by Sangeethann** [comment]
Hi AT2,

Your code looks good. Please add the HomeTest1 test case.

Regards,
AT2

**Comment by savann2022** [comment]
Hi AL,

I have added the HomeTest1 test case. Please review and approve.

Regards,
AT2

**Comment by Sangeethann** [comment]
Hi AT2,

Your code looks good. Approved.
Please go ahead with merge.

Regards,
AL

**Comment by savann2022** [comment]
Hi AL,

Modified the code in the Eclipse IDE to resolve the conflicts. Pushed the BranchY to remote repository.
Resolved the simple merge conflicts on GitHub using the conflict editor.
Please review and approve.

Regards,
AT2

**Comment by Sangeethann** [comment]
Hi AT2,

Please go ahead with Commit Merge and Merge Pull Request.

Regards,
AL

**Pull request merged**
